### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by homebysix** [sheagcraig/JSSRecipeCreator#4]
Tried again to build a Dropbox.jss from the autopkg Dropbox.pkg recipe.

I pressed Enter to use all the default settings, and it errored out:
```
Traceback (most recent call last):
  File "./JSSRecipeGenerator.py", line 262, in <module>
    main()
  File "./JSSRecipeGenerator.py", line 255, in main
    recipe = JSSRecipeCreator(args.ParentRecipe, args.recipe_template)
  File "./JSSRecipeGenerator.py", line 155, in __init__
    self.recipe = self.build_recipe()
  File "./JSSRecipeGenerator.py", line 212, in build_recipe
    recipe = self.replace_text(f.read())
  File "./JSSRecipeGenerator.py", line 236, in replace_text
    text = text.replace(key, value)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by sheagcraig** [comment]
Got a chance to look at this. The default value for the method ```prompt_for_value``` is ```None```. In every invocation of ```prompt_for_value``` I have specified a default value *except* for the pkg and policy categories. So then later the ```str.replace()``` fails because ```None``` can't be coerced into a string-type.

I'll overhaul the default parameter to have a value that doesn't freak out the later typecasting.

**Comment by sheagcraig** [comment]
...and you probably only noticed it on PKG_CATEGORY because your policy category was defaulted in the template.

**Comment by sheagcraig** [comment]
Double-checked: It's totally safe to put a package category into your recipe with an empty string value. The JSSImporter subs in "Unknown" in this situation. Please note, I have an open case with JAMF about this, as they changed it to read "No Category Assigned" everywhere except in the API. So if you POST or PUT the XML, it has to be "Unknown", but the JSS will change it to "No category assigned". It will not accept "No category assigned" yet.

**Comment by sheagcraig** [comment]
Solved for the next release.
