### ISSUE TITLE
Creator or Generator?

### ISSUE THREAD

**Issue by everetteallen** [sheagcraig/JSSRecipeCreator#6]
Minor point - all the docs talk about JSSRecipeCreator  but the script is actually JSSRecipeGenerator.py.  Did I miss something ?

**Comment by sheagcraig** [comment]
Ha! Baby brain! You didn't miss something. I'll go through and standardize the names.

**Comment by sheagcraig** [comment]
Done-it will be JSSRecipeCreator in the next release.
